### ISSUE TITLE
`getImgUrl()` 拿不到高清图源URL

### ISSUE THREAD

**Issue by Yxa2111** [1574242600/exApi#3]
一直在用这个project，首先感谢下作者，虽然不知道这个repo还在不在维护，但总之提一下。

最近发现用`getImgUrl()`拿不到2400x的图片URL，只能拿到1280分辨率的。但是在浏览器上却能拿到。看了一下，主要是没有`sk`这个cookie导致的，在进入`/g/{gid}/{gtoken}`这个页面时会set一个名为`sk`的cookie，如果没有的话就只能拿到低分辨率的。所以大概要单独保存一下这个cookie

**Comment by 1574242600** [comment]
感谢支持。

看起来 `sk` 是跟账户有关，与画廊无关。
可以帮忙看看在初始化参数 `cookies` 对象里新增 `sk` 能解决问题吗？

**Comment by 1574242600** [comment]
> 感谢支持。
> 
> 看起来 `sk` 是跟账户有关，与画廊无关。 可以帮忙看看在初始化参数 `cookies` 对象里新增 `sk` 能解决问题吗？

这样可以解决。
